@istest public class EmailHandlerTest {
    @istest Static void myTest() {
        // code_block
        EmailManager em = new EmailManager();
        em.sendMail('arivarasan.udha@gmail.com', 'greetings', 'hello');
        
        Account acc = new account ();
        acc.Name = 'Arigggvu';
        insert acc;
    }
    public static void myTest2() {
        // code_block
        EmailManager em = new EmailManager();
        em.sendMail('arivarasan.udha@gmail.com', 'greetings', 'hello');
        
        Account acc = new account ();
        acc.Name = 'Arggivu';
        insert acc;
    }
}